Document: agilent33220a
Title: Debian agilent33220a Manual
Author: <insert document author here>
Abstract: This manual describes what agilent33220a is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/agilent33220a/agilent33220a.sgml.gz

Format: postscript
Files: /usr/share/doc/agilent33220a/agilent33220a.ps.gz

Format: text
Files: /usr/share/doc/agilent33220a/agilent33220a.text.gz

Format: HTML
Index: /usr/share/doc/agilent33220a/html/index.html
Files: /usr/share/doc/agilent33220a/html/*.html
